### ISSUE TITLE
ImproperlyConfigured: Error loading MySQLdb module: dynamic module does not define init function (init_mysql)

### ISSUE THREAD

**Issue by litstrong** [litstrong/Dragon#34]
When trying to deploy on GAE, get following exception:

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 96, in LoadObject
    __import__(cumulative_path)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/Dragon/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/core/wsgi.py", line 14, in get_wsgi_application
    django.setup()
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/contrib/auth/models.py", line 41, in <module>
    class Permission(models.Model):
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/models/base.py", line 139, in __new__
    new_class.add_to_class('_meta', Options(meta, **kwargs))
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/models/base.py", line 324, in add_to_class
    value.contribute_to_class(cls, name)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/models/options.py", line 250, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/utils.py", line 240, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/base/data/home/apps/s~dragon-1042/1.386560015172332596/lib/django/db/backends/mysql/base.py", line 27, in <module>
    raise ImproperlyConfigured("Error loading MySQLdb module: %s" % e)
ImproperlyConfigured: Error loading MySQLdb module: dynamic module does not define init function (init_mysql)

**Comment by litstrong** [comment]
Check here:
http://stackoverflow.com/questions/30893734/no-module-named-mysql-google-app-engine-django/30955195

Maybe because it's a low-level C file and as it's stated in the docs GAE does not support any kind of C extensions.

Will import it in the app.yaml, since GAE already support it. Then don't need to import it into lib and then upload.
